### ISSUE TITLE
Allow to change the seconds of tolerance for the request

### ISSUE THREAD

**Issue by juliogarciag** [mgomes/api_auth#88] opened 2015-12-01 17:02 UTC
Currently the [`request_too_old?`](https://github.com/mgomes/api_auth/blob/master/lib/api_auth/base.rb#L75) method is using `900` as a hardcoded value. I think this value should depend on the use case. In my use case the value is too much. (Our servers have a timeout of 5 minutes)

Would you consider adding a PR to allow to configure `ApiAuth`'s seconds of tolerance. Maybe something like this:

``` ruby
ApiAuth.configure do |config|
  config.seconds_of_tolerance = 300
end
```

**Comment by juliogarciag** [comment] 2015-12-01 17:54
I was thinking of other way. Maybe we can just have: 

```ruby
ApiAuth.authentic?(signed_request, secret_key, seconds_of_tolerance: 300)
```

And many different calls could have a different tolerance depending on the call.

What do you think?

**Comment by awendt** [comment] 2015-12-02 09:11
Can you please look into #80? This seems to be a duplicate of it.

**Comment by kjg** [comment] 2017-05-05 18:17
Completed in #136

**Closed by kjg** 2017-05-05 18:17 UTC
